
public class studio3


{
	//dichiarazione array
	int[] numeroGiorniPerMese = new int[12];  
	//dichiarazione array multidimensionale
	int [][][] arrayConDimensione3 = new int[4][5][6];
	//dichiarazione stringa
	String titolo = "stringhe";
	
	 //PASSANDO ALLA PROGRAMMAZIONE DI OGETTI SOSTITUIAMO IL METODO "ALGORITMICO"PER AVERE 
	//ISTANZE CHE COMUNICANO DATI TRA DI LORO
	//LE CLASSI SONO IN RELAZIONE TRA DI LORO ATTRAVERSO LE EREDITARIETA
	//ASTRAZIONE,DEFINIRE ATTRIBUTI,SIMILITUDINI E DIFFERENZE CON ALTRI OGETTI
	//SECONDO IL CONTESTI DI OSSERVAZIONE
	//INCAPSULAMENTO,REALIZZA IN CODICE L'ASTRAZIONE
	//GERARCHIA,A VOLTE NON SERVE TENERE IN CONSIDERAZIONE UN'UNICA
	//ASTRAZIONE,
	//MODULARITA',CIOE DIVIDERE IL PROBLEMA IN PIU SOTTOPROBLEMI PER SEMPLIFICARLO
	//OGETTO,PUO' ESSERE TEORICO O ASTRATTO,I DEFINISCE CON STATO,CIOè STATO DELLE SUE VARIABILI
	//E COMPORTAMENTO,CIOè COME CAMBIA LO STATO E INVIA RICEVE COMUNICAZIONI
	//CON ALTRI OGGETTI,MA PER FARLO DEVE AVERE GLI OPPORTUNI METODI
	//CON LE VARIABILI PER E DA COMUNICARE,CHE VANNO DEFINITE QUINDI NELLA CLASSE
	//QUINDI LA CLASSE FA DA FONTE INIZIALE PER LE SUE ISTANZE.
	//IL COSTRUTTORE INVECE E' QUEL METODO DELLA CLASSE UTILE A CREARE LE NUOVE ISTANZE,
	//SE NON VIENE CREATO IL COMPILATORE CE L'HA DI DEFAULT
	//SE A è UNA SOTTOCLASSE DI B ALLORA EREDITA DA B STATO E COMPORTAMENTO,B SI CHIAMA
	//SUPERCLASSE DI A ,QUINDI è POSSIBILE ACCEDERE A UN'ISTANZA DI A SE è
	//POSSIBILE ACCEDERE A UN'ISTANZA DI B.
	//PER POLIMORFISMO SI PUO INTENDERE CHE AD ESMPIO UNA ISTANZA PUO CHIAMARE UN METODO
	//DELLA SUA SUPER CLASSE ,SE I METODI SONO PIU E UGUALI,IL COMPILATORE RICONOSCE LA PIU AFFINE
	//SECONDO LE VARIABILI
	//LE CLASSI ASTRATTE SERVONO A DICHIARARE CARATTERISTICHE COMUNI TRA CLASSI DELLA STESSA
	//GERARCHIA
	//CLASSE INNER-DICHIARATA DENTRO UN'ALTRA CLASSE
	//CLASSI LOCAL DEFINITE DENTRO BLOCCHI DI CODICE,SOLO LOCALI,POSSONO ANCHE ESSERE CLASSI ANONIME.	
    //PACKAGE,LIBRERIA O MODULI PIU' GENERICI.
}
